pipeline {
    agent none //  

    stages {// Estagios
        stage('Build') { // clonar o projeto
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
                
            }
        }

    }
}
